import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

// Generate image using Lovable AI (Gemini)
async function generateWithLovable(prompt: string, originalImageUrl: string): Promise<string> {
  const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
  if (!LOVABLE_API_KEY) {
    throw new Error("LOVABLE_API_KEY is not configured");
  }

  console.log("=== GENERATING WITH LOVABLE AI (Gemini) ===");
  console.log("Image type:", originalImageUrl.startsWith("data:") ? "base64" : "URL");
  console.log("Image size:", originalImageUrl.length, "chars");
  console.log("Prompt preview:", prompt.substring(0, 200) + "...");
  console.log("Timestamp:", new Date().toISOString());

  const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${LOVABLE_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "google/gemini-3-pro-image-preview",
      messages: [
        {
          role: "user",
          content: [
            {
              type: "text",
              text: prompt,
            },
            {
              type: "image_url",
              image_url: {
                url: originalImageUrl,
              },
            },
          ],
        },
      ],
      modalities: ["image", "text"],
    }),
  });

  if (!response.ok) {
    const status = response.status;
    const errorText = await response.text();
    console.error("Lovable AI error:", status, errorText);
    
    if (status === 429) {
      throw { status: 429, message: "Rate limit exceeded" };
    }
    if (status === 402) {
      throw { status: 402, message: "Payment required" };
    }
    throw new Error(`AI gateway error: ${status} - ${errorText}`);
  }

  const data = await response.json();
  console.log("=== LOVABLE AI RESPONSE ===");
  console.log("Has choices:", !!data.choices?.length);
  console.log("Has images:", !!data.choices?.[0]?.message?.images?.length);
  console.log("Text response:", data.choices?.[0]?.message?.content?.substring(0, 100));

  const imageUrl = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
  if (!imageUrl) {
    console.error("No image in response. Full response:", JSON.stringify(data).substring(0, 500));
    throw new Error("No image generated - AI may have responded with text only");
  }

  console.log("Generated image type:", imageUrl.startsWith("data:") ? "base64" : "URL");
  return imageUrl;
}

// Generate image using OpenAI DALL-E 3
async function generateWithOpenAI(prompt: string, originalImageUrl: string): Promise<string> {
  const OPENAI_API_KEY = Deno.env.get("OPENAI_API_KEY");
  if (!OPENAI_API_KEY) {
    throw new Error("OPENAI_API_KEY non configurée. Ajoutez-la dans les secrets du projet.");
  }

  console.log("=== GENERATING WITH OPENAI DALL-E 3 ===");
  console.log("Prompt preview:", prompt.substring(0, 200) + "...");

  // DALL-E 3 doesn't support image editing, so we enhance the prompt
  const enhancedPrompt = `${prompt}

Important: Create a high-quality, professional event poster design. The image should be suitable for social media sharing with a modern, clean aesthetic.`;

  const response = await fetch("https://api.openai.com/v1/images/generations", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${OPENAI_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "dall-e-3",
      prompt: enhancedPrompt,
      n: 1,
      size: "1024x1024",
      quality: "hd",
      response_format: "url",
    }),
  });

  if (!response.ok) {
    const status = response.status;
    const errorText = await response.text();
    console.error("OpenAI error:", status, errorText);
    
    if (status === 429) {
      throw { status: 429, message: "OpenAI rate limit exceeded" };
    }
    if (status === 402 || status === 401) {
      throw new Error("Clé API OpenAI invalide ou crédits insuffisants");
    }
    throw new Error(`OpenAI API error: ${status}`);
  }

  const data = await response.json();
  console.log("=== OPENAI RESPONSE ===");
  console.log("Has data:", !!data.data?.length);

  const imageUrl = data.data?.[0]?.url;
  if (!imageUrl) {
    throw new Error("No image generated by OpenAI");
  }

  return imageUrl;
}

// Generate image using Google Gemini API directly
async function generateWithGemini(prompt: string, originalImageUrl: string): Promise<string> {
  const GEMINI_API_KEY = Deno.env.get("GEMINI_API_KEY");
  if (!GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY non configurée. Ajoutez-la dans les secrets du projet.");
  }

  console.log("=== GENERATING WITH GOOGLE GEMINI (Direct API) ===");
  console.log("Image type:", originalImageUrl.startsWith("data:") ? "base64" : "URL");
  console.log("Prompt preview:", prompt.substring(0, 200) + "...");

  // Extract base64 data from data URL
  const base64Data = originalImageUrl.replace(/^data:image\/\w+;base64,/, "");

  const geminiBody = {
    contents: [
      {
        parts: [
          { text: prompt },
          {
            inline_data: {
              mime_type: "image/png",
              data: base64Data,
            },
          },
        ],
      },
    ],
    generationConfig: {
      responseModalities: ["TEXT", "IMAGE"],
    },
  };

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${GEMINI_API_KEY}`,
    {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(geminiBody),
    }
  );

  if (!response.ok) {
    const status = response.status;
    const errorText = await response.text();
    console.error("Gemini error:", status, errorText);

    if (status === 429) {
      throw { status: 429, message: "Gemini rate limit exceeded" };
    }
    if (status === 401 || status === 403) {
      throw new Error("Clé API Gemini invalide");
    }
    throw new Error(`Gemini API error: ${status}`);
  }

  const data = await response.json();
  console.log("=== GEMINI RESPONSE ===");
  console.log("Has candidates:", !!data.candidates?.length);

  // Extract image from Gemini response
  const parts = data.candidates?.[0]?.content?.parts || [];
  for (const part of parts) {
    if (part.inlineData?.data) {
      const mimeType = part.inlineData.mimeType || "image/png";
      return `data:${mimeType};base64,${part.inlineData.data}`;
    }
  }

  console.error("No image in Gemini response:", JSON.stringify(data).substring(0, 500));
  throw new Error("No image generated by Gemini");
}

// Upload base64 image to Supabase Storage
async function uploadToStorage(base64Image: string): Promise<string> {
  console.log("Uploading base64 image to storage...");
  
  const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
  const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const supabase = createClient(supabaseUrl, supabaseKey);

  // Convert base64 to blob
  const base64Data = base64Image.split(",")[1];
  const binaryData = Uint8Array.from(atob(base64Data), (c) => c.charCodeAt(0));
  const blob = new Blob([binaryData], { type: "image/png" });

  const fileName = `ai-generated/${Date.now()}-${Math.random().toString(36).substring(7)}.png`;

  const { error: uploadError } = await supabase.storage
    .from("event-images")
    .upload(fileName, blob, {
      contentType: "image/png",
      upsert: false,
    });

  if (uploadError) {
    console.error("Upload error:", uploadError);
    throw new Error("Failed to upload generated image");
  }

  const { data: urlData } = supabase.storage
    .from("event-images")
    .getPublicUrl(fileName);

  console.log("Image uploaded to:", urlData.publicUrl);
  return urlData.publicUrl;
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { mode, originalImageUrl, prompt, eventTitle, provider } = await req.json();

    console.log("=== GENERATE OVERLAY REQUEST ===");
    console.log("Mode:", mode);
    console.log("Event:", eventTitle);
    console.log("Provider requested:", provider);
    console.log("Image URL type:", originalImageUrl?.startsWith("data:") ? "base64" : originalImageUrl?.startsWith("blob:") ? "blob (ERROR)" : "http URL");
    console.log("Image URL length:", originalImageUrl?.length || 0);

    // Validate image URL - blob URLs are NOT accessible from edge functions
    if (originalImageUrl?.startsWith("blob:")) {
      console.error("ERROR: Received blob URL which is not accessible from server");
      return new Response(
        JSON.stringify({ 
          error: "Image non accessible. L'image doit être convertie en base64 avant l'envoi.",
          details: "blob: URLs cannot be accessed from the server"
        }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!originalImageUrl || !prompt) {
      return new Response(
        JSON.stringify({ error: "Paramètres manquants (image ou prompt)" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Determine which provider to use
    const selectedProvider = provider || Deno.env.get("IMAGE_GEN_PROVIDER") || "lovable";
    console.log("Using provider:", selectedProvider);

    let imageUrl: string;

    try {
      switch (selectedProvider) {
        case "openai":
          imageUrl = await generateWithOpenAI(prompt, originalImageUrl);
          break;
        case "gemini":
          imageUrl = await generateWithGemini(prompt, originalImageUrl);
          break;
        case "lovable":
        default:
          imageUrl = await generateWithLovable(prompt, originalImageUrl);
          break;
      }
    } catch (genError: any) {
      console.error("Generation error:", genError);
      
      // Handle rate limit and payment errors
      if (genError.status === 429) {
        return new Response(
          JSON.stringify({ error: "Limite de requêtes atteinte. Réessayez dans quelques minutes.", status: 429 }),
          { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      if (genError.status === 402) {
        return new Response(
          JSON.stringify({ error: "Crédits insuffisants. Rechargez votre compte.", status: 402 }),
          { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }
      throw genError;
    }

    // If the image is base64, upload it to storage
    if (imageUrl.startsWith("data:image")) {
      imageUrl = await uploadToStorage(imageUrl);
    }

    console.log("=== SUCCESS ===");
    console.log("Final image URL:", imageUrl.substring(0, 100) + "...");

    return new Response(
      JSON.stringify({ imageUrl, provider: selectedProvider }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Generate overlay error:", error);
    return new Response(
      JSON.stringify({ 
        error: error instanceof Error ? error.message : "Erreur inconnue lors de la génération" 
      }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
